name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore Packages
      run: nuget restore TalkerCounter.sln

    - name: Build solution
      run: msbuild TalkerCounter.sln -t:rebuild -property:Configuration=Release